Test
codinglabsau/learn pull request #2
Opened 2022-09-07 03:59 UTC by ati7697

used foreign keys in migrations, firstOrCreate for bootstrap command, guarded attribute on Lesson model, create new models,  created a relationship between models.

2022-09-07 04:50 UTC, vrodriguero reviewed
Hi Ati :) 
Great work! 
I just left a few suggestions and change requests for some of the proposed changes. Let me know if you have any questions. 

Happy coding :)

2022-09-07 04:50 UTC, vrodriguero commented on app/Models/Course_User.php
> +<?php
I think that we will not need the pivot models. 
We can define the many-to-many relationship from the main models and that should be enough. 

Another tip is that when we create Pivot models the Laravel convention is to have the model name be in PascalCase, so for example a pivot for the `course_user` table would be named `CourseUser` 

But, for this use case we will not need this model, so you can delete it

2022-09-07 04:50 UTC, vrodriguero commented on app/Models/Lesson.php
> +    public function lesson_user()
This can be changed to:
```
public function users(): BelongsToMany
{
    return $this->belongsToMany(User::class)
}
```

2022-09-07 04:50 UTC, vrodriguero commented on app/Models/Lesson_User.php
> +
This file can also be deleted

2022-09-07 04:50 UTC, vrodriguero commented on package-lock.json
> +    "name": "learn",
This change can be reverted. It is probably a change made automatically when you ran `npm install`.  I recommend, running  `npm ci` instead, so you will not need to worry with the package-lock being altered accidentally :)

2022-09-07 04:50 UTC, vrodriguero commented on app/Models/User.php
> +    public function lesson_user()
Similar to the previous comment on the Lesson, this can be removed and the relationship can be replaced with the many to many.

So it would look something similar to:
```
public function lessons(): BelongsToMany
{
   return $this->belongsToMany(Lesson::class)
}
```

2022-09-07 04:50 UTC, vrodriguero commented on app/Models/User.php
> +    public function course_user()
Same as the comment above ☝️

2022-09-07 04:51 UTC, vrodriguero requested changes
The comments above are the suggested changes

2022-09-12 23:17 UTC, ati7697 commented on app/Models/Course_User.php
> +<?php
As we talked last week with Steave, he told us to have pivot tables, so I thought we need to have models for them too.

2022-09-12 23:18 UTC, ati7697 commented on app/Models/Course_User.php
> +<?php
How we are going to show the relationship between user and course, user and lesson?

2022-09-12 23:18 UTC, ati7697 commented on app/Models/Lesson_User.php
> +
okay

2022-09-12 23:22 UTC, vrodriguero commented on app/Models/Course_User.php
> +<?php
So the pivot tables will exist, but we are able to access them without having to set models for it :) 

If you see the comments below, the lesson will access users by having a `users()` relationship in the Lesson model :)

2022-09-12 23:25 UTC, vrodriguero commented on app/Models/Course_User.php
> +<?php
Once you set that, Laravel knows that this is a `many-to-many` relationship and if the table name is according to the expected convention, Laravel will automatically know which table is the pivot.

2022-09-12 23:29 UTC, ati7697 commented on app/Models/Course_User.php
> +<?php
okay, now I understand! thankssss!

2022-09-13 00:04 UTC, vrodriguero requested changes
Almost done :) The only thing left is to revert the package.lock change and I can approve this request :)

2022-09-13 01:49 UTC, vrodriguero requested changes

2022-09-13 01:49 UTC, vrodriguero commented on package-lock.json
> +                "bootstrap": "^5.1.3",
Hey Ati can you revert these changes on the package-lock?

2022-09-13 03:36 UTC, vrodriguero approved these changes

2022-09-13 22:56 UTC, merged